$("button").click(function(){
    $('html,body').animate({
        scrollTop:$(".seccond").oofset().top},slow);
});
$(window).scroll(function(){
    $('html,body').animate({
        scrollTop:$("#about").offset().top},2000);
});
$("button").click(function(){
    $('html,body').animate({
        scrollTop:$(".seccond").oofset().top},slow);
});
$(window).scroll(function(){
    $('html,body').animate({
        scrollTop:$("#skill").offset().top},2000);
});
$(window).scroll(function(){
    $('html,body').animate({
        scrollTop:$("#project").offset().top},2000);
});
$(window).scroll(function(){
    $('html,body').animate({
        scrollTop:$("#contact").offset().top},2000);
});